name: "Check Self Hosted Runners"
description: "Check whether self hosted runner is present in org"
author: "Red Hat"
branding:
  icon: circle
  color: red
inputs:
  github_token:
    description: "Github Access Token with org and repo level permissions"
    required: true
  repository_path:
    description: "The repo path in which to check for the self hosted runner. It can also take the name of the org"
    required: true
outputs:
  runner_present:
    description: "Boolean value which signifies the presence of self hosted runner"
runs:
  using: 'node12'
  main: 'dist/index.js'