name: Test self-hosted runner in org
on: [ push, workflow_dispatch ]

jobs:
  install-runner:
    runs-on: ubuntu-20.04
    name: Install org runner
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - uses: redhat-actions/oc-login@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SANDBOX_URL }}
          openshift_token: ${{ secrets.TIM_OPENSHIFT_TOKEN }}
          namespace: tetchell-code
          insecure_skip_tls_verify: true

      - name: Install self hosted runner into org
        uses: ./
        with:
          github_pat: ${{ secrets.ORG_TOKEN }}
          runner_location: redhat-actions
          runner_labels: org-label, org-label-2
          # helm_release_name: tim-org-runner
          runner_replicas: 2

  test-selfhosted:
    runs-on: [ self-hosted, org-label, org-label-2 ]
    needs: install-runner

    steps:
      - run: "hostname"
