name: Test self-hosted runner in repo
on: [ push, workflow_dispatch ]

jobs:
  test-action-job:
    runs-on: ubuntu-20.04
    name: Check for repo runner
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Check self hosted runner
        id: check_runner
        uses: ./
        with:
          github_pat: ${{ secrets.REPO_TOKEN }}
          runner_labels: label1, label2, label3
          helm_release_name: tim-repo-runner
