name: Tear down repository runners
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ teardown_runners ]
  schedule:
    # Every sunday night
    - cron: "0 23 * * SUN"

jobs:
  tear-down-runners:
    name: Tear down repository runners
    runs-on: ubuntu-20.04
    env:
      HELM_RELEASE_NAME: "node-runner"

    steps:
      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true

      - run: helm ls

      # If we were running in the same workflow as the self-hosted runner installation,
      # we could use ${{ <job>.outputs.helm_release_name }} to get the release name
      - run: |
          if helm status ${{ env.HELM_RELEASE_NAME }}; then
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Release ${{ env.HELM_RELEASE_NAME }} not found"
          fi

      - run: helm uninstall ${{ env.HELM_RELEASE_NAME }}
        if: env.RELEASE_EXISTS == 'true'
